[project]
name = "oppna-bolagsdata"
version = "0.1.0"
description = "Open Swedish company data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.0",
    "duckdb>=1.0.0",
    "requests>=2.31.0",
]
