name: Update the data
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * 1' # 1AM every Monday
jobs:
  scrape:
    name: Update the data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install .
      - name: Run main.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python main.py